language: emacs-lisp
os:
  - linux
  - osx
sudo: required
before_install:
  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
install:
  - git clone https://github.com/rejeep/evm.git ~/.evm
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.5-bin
script:
  - ./run-travis-ci.sh
notifications:
  email:
    - reximkut@gmail.com
