language: emacs-lisp
os:
  - linux
  - osx
before_install:
  - export PATH="$HOME/.cask/bin:$PATH"
  - export PATH="$HOME/.evm/bin:$PATH"
install:
  - git clone https://github.com/rejeep/evm.git "$HOME/.evm"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - ./run-travis-ci.sh
notifications:
  email:
    - reximkut@gmail.com
